export const HetznerImages = [
    {
        id: 15512617,
        type: "system",
        status: "available",
        name: "ubuntu-20.04",
        description: "Ubuntu 20.04",
        image_size: null,
        disk_size: 5,
        created: "2020-04-23T17:55:14+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "ubuntu",
        os_version: "20.04",
        rapid_deploy: true,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "x86",
    },
    {
        id: 40093059,
        type: "app",
        status: "available",
        name: "lamp",
        description: "lamp",
        image_size: null,
        disk_size: 40,
        created: "2021-06-08T06:21:07+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "ubuntu",
        os_version: "unknown",
        rapid_deploy: false,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "x86",
    },
    {
        id: 40093134,
        type: "app",
        status: "available",
        name: "wordpress",
        description: "wordpress",
        image_size: null,
        disk_size: 40,
        created: "2021-06-08T06:21:42+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "ubuntu",
        os_version: "unknown",
        rapid_deploy: false,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "x86",
    },
    {
        id: 40093140,
        type: "app",
        status: "available",
        name: "jitsi",
        description: "jitsi",
        image_size: null,
        disk_size: 40,
        created: "2021-06-08T06:21:47+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "ubuntu",
        os_version: "unknown",
        rapid_deploy: false,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "x86",
    },
    {
        id: 40093190,
        type: "app",
        status: "available",
        name: "nextcloud",
        description: "nextcloud",
        image_size: null,
        disk_size: 40,
        created: "2021-06-08T06:22:07+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "ubuntu",
        os_version: "unknown",
        rapid_deploy: false,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "x86",
    },
    {
        id: 40093247,
        type: "app",
        status: "available",
        name: "docker-ce",
        description: "docker-ce",
        image_size: null,
        disk_size: 40,
        created: "2021-06-08T06:22:47+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "ubuntu",
        os_version: "unknown",
        rapid_deploy: false,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "x86",
    },
    {
        id: 40093435,
        type: "app",
        status: "available",
        name: "gitlab",
        description: "gitlab",
        image_size: null,
        disk_size: 40,
        created: "2021-06-08T06:24:08+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "ubuntu",
        os_version: "unknown",
        rapid_deploy: false,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "x86",
    },
    {
        id: 45557056,
        type: "system",
        status: "available",
        name: "debian-11",
        description: "Debian 11",
        image_size: null,
        disk_size: 5,
        created: "2021-08-16T11:12:01+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "debian",
        os_version: "11",
        rapid_deploy: true,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "x86",
    },
    {
        id: 45780948,
        type: "system",
        status: "available",
        name: "rocky-8",
        description: "Rocky Linux 8",
        image_size: null,
        disk_size: 5,
        created: "2021-08-19T06:30:23+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "rocky",
        os_version: "8",
        rapid_deploy: true,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "x86",
    },
    {
        id: 59752342,
        type: "system",
        status: "available",
        name: "centos-stream-9",
        description: "CentOS Stream 9",
        image_size: null,
        disk_size: 5,
        created: "2022-01-27T07:52:03+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "centos",
        os_version: "Stream 9",
        rapid_deploy: true,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "x86",
    },
    {
        id: 67794396,
        type: "system",
        status: "available",
        name: "ubuntu-22.04",
        description: "Ubuntu 22.04",
        image_size: null,
        disk_size: 5,
        created: "2022-04-21T13:32:38+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "ubuntu",
        os_version: "22.04",
        rapid_deploy: true,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "x86",
    },
    {
        id: 73721460,
        type: "app",
        status: "available",
        name: "prometheus-grafana",
        description: "prometheus-grafana",
        image_size: null,
        disk_size: 40,
        created: "2022-06-20T08:27:16+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "ubuntu",
        os_version: "unknown",
        rapid_deploy: false,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "x86",
    },
    {
        id: 76766499,
        type: "system",
        status: "available",
        name: "rocky-9",
        description: "Rocky Linux 9",
        image_size: null,
        disk_size: 5,
        created: "2022-07-20T13:55:52+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "rocky",
        os_version: "9",
        rapid_deploy: true,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "x86",
    },
    {
        id: 80379320,
        type: "app",
        status: "available",
        name: "wireguard",
        description: "wireguard",
        image_size: null,
        disk_size: 40,
        created: "2022-08-24T14:08:55+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "ubuntu",
        os_version: "unknown",
        rapid_deploy: false,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "x86",
    },
    {
        id: 101588646,
        type: "app",
        status: "available",
        name: "owncast",
        description: "owncast",
        image_size: null,
        disk_size: 40,
        created: "2023-03-01T10:21:43+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "ubuntu",
        os_version: "unknown",
        rapid_deploy: false,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "x86",
    },
    {
        id: 101588775,
        type: "app",
        status: "available",
        name: "photoprism",
        description: "photoprism",
        image_size: null,
        disk_size: 40,
        created: "2023-03-01T10:22:15+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "ubuntu",
        os_version: "unknown",
        rapid_deploy: false,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "x86",
    },
    {
        id: 102456737,
        type: "app",
        status: "available",
        name: "rustdesk",
        description: "rustdesk",
        image_size: null,
        disk_size: 40,
        created: "2023-03-08T14:01:35+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "ubuntu",
        os_version: "unknown",
        rapid_deploy: false,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "x86",
    },
    {
        id: 103907339,
        type: "system",
        status: "available",
        name: "centos-stream-9",
        description: "CentOS Stream 9",
        image_size: null,
        disk_size: 5,
        created: "2023-03-20T10:06:35+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "centos",
        os_version: "Stream 9",
        rapid_deploy: true,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "arm",
    },
    {
        id: 103907373,
        type: "system",
        status: "available",
        name: "debian-11",
        description: "Debian 11",
        image_size: null,
        disk_size: 5,
        created: "2023-03-20T10:06:43+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "debian",
        os_version: "11",
        rapid_deploy: true,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "arm",
    },
    {
        id: 103907722,
        type: "system",
        status: "available",
        name: "rocky-8",
        description: "Rocky Linux 8",
        image_size: null,
        disk_size: 5,
        created: "2023-03-20T10:08:25+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "rocky",
        os_version: "8",
        rapid_deploy: true,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "arm",
    },
    {
        id: 103907769,
        type: "system",
        status: "available",
        name: "rocky-9",
        description: "Rocky Linux 9",
        image_size: null,
        disk_size: 5,
        created: "2023-03-20T10:08:36+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "rocky",
        os_version: "9",
        rapid_deploy: true,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "arm",
    },
    {
        id: 103908070,
        type: "system",
        status: "available",
        name: "ubuntu-20.04",
        description: "Ubuntu 20.04",
        image_size: null,
        disk_size: 5,
        created: "2023-03-20T10:09:51+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "ubuntu",
        os_version: "20.04",
        rapid_deploy: true,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "arm",
    },
    {
        id: 103908130,
        type: "system",
        status: "available",
        name: "ubuntu-22.04",
        description: "Ubuntu 22.04",
        image_size: null,
        disk_size: 5,
        created: "2023-03-20T10:10:04+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "ubuntu",
        os_version: "22.04",
        rapid_deploy: true,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "arm",
    },
    {
        id: 104788983,
        type: "system",
        status: "available",
        name: "alma-8",
        description: "AlmaLinux 8",
        image_size: null,
        disk_size: 5,
        created: "2023-03-27T11:32:49+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "alma",
        os_version: "8",
        rapid_deploy: true,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "x86",
    },
    {
        id: 104788996,
        type: "system",
        status: "available",
        name: "alma-9",
        description: "AlmaLinux 9",
        image_size: null,
        disk_size: 5,
        created: "2023-03-27T11:33:04+00:00",
        created_from: null,
        bound_to: null,
        os_flavor: "alma",
        os_version: "9",
        rapid_deploy: true,
        protection: {
            delete: false,
        },
        deprecated: null,
        labels: {},
        deleted: null,
        architecture: "x86",
    },
] as const;
