deployments:
    - deployment_name: test
      provider: hetzner
      location: ash
      description: Docker Test Deployment
      services:
          web:
              instances: 2
              clusters: 1
              server_type: cpx11
              dir_mappings:
                  - src: .
                    dst: /app
                  - src: ./secrets/prod.env
                    dst: /app/.env
              dependencies:
                  apt:
                      - rsync
                  turboci:
                      - bun
                      - node
              run:
                  preflight:
                      work_dir: /app
                      cmds:
                          - bun add -g pm2
                          - pm2 kill
                          - bun install
                  start:
                      work_dir: /app
                      cmds:
                          - pm2 start "bunx next start"
                  postflight:
                      cmds:
                          - pm2 list
              healthcheck:
                  cmd: curl http://localhost:3000/api/healthcheck
                  test: Server Running
              logs:
                  - pm2 logs
          db:
              instances: 1
              clusters: 1
              dependencies:
                  apt:
                      - mariadb-server
              dir_mappings:
                  - src: ./db
                    dst: /db-setup
              init:
                  - cp /db-setup/setup.sh /usr/local/bin/db-setup
                  - chmod +x /usr/local/bin/db-setup
                  - db-setup
envs:
    - GIT_HOST=https://git.tben.me
