# yaml-language-server: $schema=../../../../schema/turboci.schema.json

deployments:
    - deployment_name: base_lb
      provider: hetzner
      location: ash
      description: >
          Base Load Balancer config
      services:
          api:
              instances: 1
              clusters: 1
              server_type: cpx11
              dependencies:
                  turboci:
                      - bun
                      - node
              dir_mappings:
                  - dst: /app/server
                    src: ./server
              run:
                  preflight:
                      cmds:
                          - bun add -g pm2
                          - pm2 kill
                          - cd /app
                          - chmod +x ./server/setup.sh && ./server/setup.sh
                          - ls -laF
                  start:
                      work_dir: /app
                      cmds:
                          - pm2 start "bun server/serve.ts"
          lb:
              type: load_balancer
              target_services:
                  - service_name: api
                    port: 3000
                    locations:
                        - match: "/ws"
                          target_port: 5000
                        - match: "/api"
                          target_path: "/api"
                          rate_limit:
                              rate: "10r/s"
                        - match: "/public/"
                          no_proxy: true
                          directives:
                              alias: "/static/"
                              try files: "$uri $uri/ =404"
