deployments:
    - deployment_name: github_public_repo
      provider: hetzner
      location: ash
      description: Git Test Deployment
      services:
          web:
              instances: 5
              clusters: 2
              git:
                  repo_url: https://github.com/medusajs/nextjs-starter-medusa.git
                  work_dir: /app
                  public_repo: true
              dependencies:
                  turboci:
                      - bun
                      - node
              run:
                  preflight:
                      work_dir: /app
                      cmds:
                          - bun add -g yarn
                          - bun add -g pm2
                          - pm2 kill
                          - ls -laF
                          - pwd
                          - mv .env.template .env.local || echo ".env.template already moved"
                          - yarn
                  start:
                      work_dir: /app
                      cmds:
                          - pm2 start "yarn dev"
              logs:
                  - pm2 logs
          load_balancer:
              type: load_balancer
              target_services:
                  - service_name: web
                    port: 8000
