export const AppNames = {
    TurboCIDefaultDir: ".turboci",
    TurboCISSHKeyName: "turboci",
    TurboCILabelNameKey: "turboci_deployment_name",
    TurboCILabelServiceNameKey: "turboci_service_name",
    DefaultConfigFile: "config.yaml",
    DefaultConfigTSFile: "config.ts",
    FileFlag: "-f, --file <path>",
    SkipServiceFlag: "-s, --skip <service-name>",
    TargetServicesFlag: "-t, --target <service-name>",
    HetznerAPIKeyEnvName: "TURBOCI_HETZNER_API_KEY",
    AWSAccessKeyEnvName: "TURBOCI_AWS_ACCESS_KEY",
    AWSSecretAccessKeyEnvName: "TURBOCI_AWS_SECRET_ACCESS_KEY",
    AzureSubscriptionIdEnvName: "TURBOCI_AZURE_SUBSCRIPTION_ID",
    AzureTenantIdEnvName: "TURBOCI_AZURE_TENANT_ID",
    AzureClientIdEnvName: "TURBOCI_AZURE_CLIENT_ID",
    AzureClientSecretEnvName: "TURBOCI_AZURE_CLIENT_SECRET",
    GithubAPIKey: "TURBOCI_GITHUB_API_KEY",
    GiteaAPIKey: "TURBOCI_GITEA_API_KEY",
    GiteaAPIUsername: "TURBOCI_GITEA_API_Username",
    GitlabAPIKey: "TURBOCI_GITLAB_API_KEY",
    GCPServiceAccountEmail: "TURBOCI_GCP_SERVICE_ACCOUNT_EMAIL",
    GCPProjectID: "TURBOCI_GCP_PROJECT_ID",
    GCPServiceAccountPrivateKey: "TURBOCI_GCP_SERVICE_ACCOUNT_PRIVATE_KEY",
    RsyncDefaultIgnoreFile: "turboci.ignore",
    TurbosyncPreflightDefaultFile: "turboci.preflight.sh",
    TurbosyncPostflightDefaultFile: "turboci.postflight.sh",
    TurbosyncStartDefaultFile: "turboci.start.sh",
    LoadBalancerUpstreamName: "turboci_load_balancer_upstream",
    LoadBalancerBakcupUpstreamName: "turboci_load_balancer_backup_upstream",
    LoadBalancerServerName: "turboci_lb.local",
    CertbotSSLCertName: "turboci",
    HealthcheckErrorMsg: "TurboCI Healthcheck Error",
} as const;
