# yaml-language-server: $schema=https://raw.githubusercontent.com/Moduletrace/turboci/refs/heads/main/schema/turboci.schema.json

deployments:
    - deployment_name: next-js
      provider: hetzner
      location: ash
      description: Next JS application
      services:
          app:
              instances: 1
              clusters: 1
              server_type: cpx11
              dependencies:
                  turboci:
                      - bun
                      - node
              dir_mappings:
                  - dst: /app
                    src: ./latest-next-app
                    use_gitignore: true
              run:
                  preflight:
                      work_dir: /app
                      cmds:
                          - bun install
                          - bun run build
                  start:
                      work_dir: /app
                      cmds:
                          - bun start
          lb:
              type: load_balancer
              target_services:
                  - service_name: app
                    port: 3000
